name: Mirror to GitLab
on:
  push:
    branches: ["**"]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push mirror to GitLab
        env:
          GL_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GL_REPO:  ${{ secrets.GITLAB_REPO }}
        run: |
          # Remove any accidental newlines from the token
          GL_TOKEN_CLEAN=$(echo -n "$GL_TOKEN" | tr -d '\r\n')
          # Build HTTPS URL with token
          GITLAB_URL="https://oauth2:${GL_TOKEN_CLEAN}@${GL_REPO#https://}"
          git remote add gitlab "$GITLAB_URL"
          git push --mirror gitlab
