name: Mirror to GitLab
on:
  push:
    branches: ["**"]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push mirror to GitLab
        env:
          GL_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GL_REPO:  ${{ secrets.GITLAB_REPO }}
        run: |
          set -e
          # Clean any accidental CR/LF or spaces
          GL_TOKEN_CLEAN=$(printf "%s" "$GL_TOKEN" | tr -d '\r\n')
          GL_REPO_CLEAN=$(printf "%s" "$GL_REPO"  | tr -d '\r\n')
          # Strip leading https:// if present
          GL_REPO_STRIPPED=${GL_REPO_CLEAN#https://}
          GITLAB_URL="https://oauth2:${GL_TOKEN_CLEAN}@${GL_REPO_STRIPPED}"
          git remote add gitlab "$GITLAB_URL"
          git push --mirror gitlab
