name: Mirror to GitLab
on:
  push:
    branches: ["**"]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push mirror to GitLab
        run: |
          git remote add gitlab "${{ secrets.GITLAB_URL }}"
          git push --mirror gitlab
